version: "3.8"

services:
  api:
    # container_name: nestjs_api_dev
    # image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    command: npm run start:debug
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - "8080:3000"
      - "9229:9229"

  postgres:
    image: postgres:10.4
    ports:
      - "35000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db

    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    restart: unless-stopped
