version: "3.8"

services:
  api:
    # container_name: nestjs_api_dev
    # image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    command: npm run start:debug
    depends_on:
      - postgres
    env_file:
      - ./src/common/envs/.env
    ports:
      - "8080:3000"
      - "9229:9229"

  postgres:
    image: postgres:10.4
    ports:
      - "35000:5432"
    env_file:
      - ./src/common/envs/.env

    volumes:
      - ./postgres-data:/var/lib/postgresql/data

    restart: unless-stopped
